name: Code analysis
on: pull_request
jobs:
  gradle:
    name: Detekt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          generate-job-summary: false

      - name: Execute Detekt task
        run: ./gradlew detektAll

      - name: Archive report
        uses: actions/upload-artifact@v3
        with:
          name: Detekt report
          path: build/reports/detekt/

      - name: Add report to action summary
        run: |
          detekt_report_spoiler() {
            echo "<details>"
            echo "  <summary>$1</summary>"
            echo ""
            cat "$2"
            echo "</details>"
            echo ""
          }
          
          echo "# Common" >> $GITHUB_STEP_SUMMARY
          detekt_report_spoiler "Main" "build/reports/detekt/metadataCommonMain.md" >> $GITHUB_STEP_SUMMARY
          
          echo "# Backend" >> $GITHUB_STEP_SUMMARY
          detekt_report_spoiler "Main" "build/reports/detekt/backendMain.md" >> $GITHUB_STEP_SUMMARY
          detekt_report_spoiler "Test" "build/reports/detekt/backendTest.md" >> $GITHUB_STEP_SUMMARY
          
          echo "# Frontend" >> $GITHUB_STEP_SUMMARY
          detekt_report_spoiler "Main" "build/reports/detekt/frontendMain.md" >> $GITHUB_STEP_SUMMARY
          detekt_report_spoiler "Test" "build/reports/detekt/frontendTest.md" >> $GITHUB_STEP_SUMMARY
          
